### ISSUE TITLE
Update promoted search results

### ISSUE THREAD

**Issue by v0nerd** [miracletalent/PFNexus-NextJS-Typescript-Jest-Storybook#1]
_Continue_ to look at more involved and comprehensive solutions using Elastic Search. we have noticed that **promoted search results** would actually solve the majority of our problems if they had the ability to include external pages. In fact, in some ways promoted search results could actually be better than indexing these pages for the following reasons:

1. Even though we want to add external pages to our search results, there is a lot of content on these pages we would want to keep out of the index. Though we could index these and fine tune the results, it seems heavy handed.
2. In-site searching is used by a very small fraction of our users. The large majority of them just use Google to search our site anyhow. We're most worried about a set of known searches.

**Comment by forwardtoward** [comment]
Seems to be now.
